#!/usr/bin/env bash
# ============================================================================
# patch-ios-privacy-manifest.sh — give the APP TARGET its own PrivacyInfo.xcprivacy.
#
#   usage:  scripts/patch-ios-privacy-manifest.sh [path-to-repo]
#
# WHY THIS EXISTS
# ---------------
# Capacitor's own frameworks ship privacy manifests
# (node_modules/@capacitor/ios/Capacitor/Capacitor/PrivacyInfo.xcprivacy), which covers
# the THIRD-PARTY SDK half of Apple's requirement. The APP target had none at all.
#
# ScootSteps collects nothing and calls no required-reason API from its own code, so
# the correct manifest is an explicit set of empty/false declarations. Shipping that
# is better than shipping nothing: it is the machine-readable form of the "Data Not
# Collected" answer given in App Store Connect, and if the two ever disagree that is a
# 5.1.1 problem. An absent manifest cannot agree with anything.
#
# WHY A PATCH SCRIPT
# ------------------
# ios/ is gitignored and regenerated by `npx cap add ios` on every CI build, so the
# file AND its Xcode target membership have to be re-created each time. A resource
# that exists on disk but is not in the target's Resources build phase is not copied
# into the .app — it would look done and ship nothing.
#
# IDEMPOTENT (guarded on the marker) and SELF-VERIFYING: it re-parses project.pbxproj
# with plutil afterwards and exits non-zero if the project no longer parses or the
# resource did not land, so a broken edit fails the build here rather than at archive.
# ============================================================================
set -uo pipefail

APP="${1:-.}"
[ -d "$APP" ] || { echo "patch-privacy-manifest: no such directory: $APP" >&2; exit 2; }
APP="$(cd "$APP" && pwd)"
PBX="$APP/ios/App/App.xcodeproj/project.pbxproj"
MANIFEST="$APP/ios/App/App/PrivacyInfo.xcprivacy"

[ -f "$PBX" ] || { echo "patch-privacy-manifest: $PBX not found — run 'npx cap add ios' first" >&2; exit 2; }

# ---- 1. the manifest itself ------------------------------------------------------
# NSPrivacyTracking      false : no tracking, no ATT prompt, no IDFA.
# NSPrivacyTrackingDomains empty : nothing to list; the only hosts contacted are
#                          Apple's own preview CDN / search API, which are not tracking.
# NSPrivacyCollectedDataTypes empty : matches the ASC answer "Data Not Collected".
# NSPrivacyAccessedAPITypes  empty : the app target's own code (AppDelegate + the
#                          AVAudioSession block) touches no required-reason API.
#                          Capacitor's framework declares its own in its own manifest.
cat > "$MANIFEST" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSPrivacyTracking</key>
	<false/>
	<key>NSPrivacyTrackingDomains</key>
	<array/>
	<key>NSPrivacyCollectedDataTypes</key>
	<array/>
	<key>NSPrivacyAccessedAPITypes</key>
	<array/>
</dict>
</plist>
PLIST
plutil -lint "$MANIFEST" >/dev/null || { echo "patch-privacy-manifest: generated manifest is not a valid plist" >&2; exit 1; }

# ---- 2. add it to the App target's Resources build phase --------------------------
python3 - "$PBX" <<'PY'
import re, sys

path = sys.argv[1]
src = open(path, encoding="utf-8").read()

FILE_REF  = "SS00PRIV0001"          # stable, deliberately outside Xcode's 24-hex-digit space
BUILD_REF = "SS00PRIV0002"

if FILE_REF in src:
    print("==> already patched — nothing to do")
    sys.exit(0)

# a) PBXBuildFile entry
m = re.search(r'/\* Begin PBXBuildFile section \*/\n', src)
if not m:
    sys.exit("patch-privacy-manifest: no PBXBuildFile section")
src = (src[:m.end()]
       + "\t\t%s /* PrivacyInfo.xcprivacy in Resources */ = {isa = PBXBuildFile; fileRef = %s /* PrivacyInfo.xcprivacy */; };\n" % (BUILD_REF, FILE_REF)
       + src[m.end():])

# b) PBXFileReference entry
m = re.search(r'/\* Begin PBXFileReference section \*/\n', src)
if not m:
    sys.exit("patch-privacy-manifest: no PBXFileReference section")
src = (src[:m.end()]
       + '\t\t%s /* PrivacyInfo.xcprivacy */ = {isa = PBXFileReference; lastKnownFileType = text.plist.xml; path = PrivacyInfo.xcprivacy; sourceTree = "<group>"; };\n' % FILE_REF
       + src[m.end():])

# c) into the Resources build phase (the one that already carries Assets.xcassets)
m = re.search(r'(isa = PBXResourcesBuildPhase;.*?files = \(\n)', src, re.S)
if not m:
    sys.exit("patch-privacy-manifest: no PBXResourcesBuildPhase files list")
src = (src[:m.end(1)]
       + "\t\t\t\t%s /* PrivacyInfo.xcprivacy in Resources */,\n" % BUILD_REF
       + src[m.end(1):])

# d) into the group that owns Info.plist, so it sits beside it in the navigator
m = re.search(r'(\n\t\t\t\t[0-9A-Fa-f]{24} /\* Info\.plist \*/,\n)', src)
if m:
    src = src[:m.end(1)] + "\t\t\t\t%s /* PrivacyInfo.xcprivacy */,\n" % FILE_REF + src[m.end(1):]
else:
    print("!! note: Info.plist group entry not found — file is in the build phase but not grouped")

open(path, "w", encoding="utf-8").write(src)
print("==> added PrivacyInfo.xcprivacy to the App target's Resources")
PY
rc=$?
[ "$rc" = 0 ] || { echo "patch-privacy-manifest: patch step failed (rc=$rc)" >&2; exit "$rc"; }

# ---- 3. verify, loudly ------------------------------------------------------------
fail=0
plutil -convert xml1 "$PBX" -o /dev/null 2>/dev/null \
  || { echo "patch-privacy-manifest: VERIFY FAILED — project.pbxproj no longer parses as a plist" >&2; fail=1; }
grep -qF 'PrivacyInfo.xcprivacy in Resources */,' "$PBX" \
  || { echo "patch-privacy-manifest: VERIFY FAILED — not in the Resources build phase" >&2; fail=1; }
grep -qF 'path = PrivacyInfo.xcprivacy;' "$PBX" \
  || { echo "patch-privacy-manifest: VERIFY FAILED — no file reference" >&2; fail=1; }
# The Resources entry must be inside the PBXResourcesBuildPhase block, not merely present.
python3 - "$PBX" <<'PY' || fail=1
import re, sys
src = open(sys.argv[1], encoding="utf-8").read()
m = re.search(r'isa = PBXResourcesBuildPhase;.*?files = \((.*?)\);', src, re.S)
if not m or "PrivacyInfo.xcprivacy" not in m.group(1):
    sys.exit("patch-privacy-manifest: VERIFY FAILED — manifest is not inside the Resources phase file list")
PY

[ "$fail" = 0 ] || exit 1
echo "==> verified: PrivacyInfo.xcprivacy exists, is a valid plist, and is a Resource of the App target"
echo "    (NSPrivacyTracking=false, no collected data types, no required-reason APIs)"
